mattfenwick/cyclonus

pkg/cli/analyze.go, pkg/cli/compare.go, pkg/cli/generate.go, pkg/cli/probe.go, pkg/cli/syntheticprobe.go, pkg/cli/targets.go, pkg/cli/traffic.go, pkg/connectivity/interpreter.go, pkg/kube/kubernetes.go
=> allow KUBECONFIG env by not setting unnecessary overrides

pkg/cli/generate.go, pkg/cli/probe.go, pkg/connectivity/interpreter.go, pkg/connectivity/setup.go, pkg/kube/kubernetes.go
=> add option to clean up namespaces after tests

cmd/recipes/main.go, pkg/connectivity/synthetic/resource-printer.go, pkg/connectivity/synthetic/resources.go, pkg/recipes/policies.go, pkg/recipes/recipe.go
Example:
```
➜  cyclonus git:(recipes) ✗ go run cmd/recipes/main.go 
INFO[0000] running synthetic probe on port 80, protocol TCP 
+---------+------------------+---------------------+-----------------+------------------------+---------------+
|  TYPE   | TARGET NAMESPACE | TARGET POD SELECTOR |      PEER       |     PORT/PROTOCOL      | SOURCE RULES  |
+---------+------------------+---------------------+-----------------+------------------------+---------------+
| Ingress | default          | Match labels:       |                 |                        | /web-deny-all |
|         |                  |   app: web          |                 |                        |               |
+---------+------------------+---------------------+-----------------+------------------------+--------------- …
```
=> add examples for netpol recipes

pkg/cli/generate.go, pkg/cli/probe.go, pkg/connectivity/probe/job.go, pkg/connectivity/probe/pod.go
Fixes #19 
To use:
```
go run cmd/cyclonus/main.go generate --mode=experimental --server-protocol udp
```
=> add udp support using updated agnhost image

examples/run.sh, pkg/cli/analyze.go, pkg/cli/utils.go, pkg/connectivity/probe/jobrunner.go, pkg/kube/kubernetes.go
=> refactor analyze command to read more resources from kube

kind/cilium/setup.sh
Notes about cilium + kind on fedora 33
=> Add Fedora 33 tips to cilium/KinD setup script

kind/antrea/setup.sh
=> Update antrea/kind version to 0.12.2

kind/cilium/setup.sh
=> Update cilium/kind version to 1.9.5

pkg/cli/analyze.go, pkg/kube/networkpolicy.go
=> add parse mode under analyze command

.github/workflows/kind_ovn.yml, hack/ovn-kubernetes/.gitignore, hack/ovn-kubernetes/cyclonus-job-github-action.yaml, hack/ovn-kubernetes/github-action.sh, hack/ovn-kubernetes/patch-fedora33-cg0-enabled.patch, hack/ovn-kubernetes/setup-kind.sh, hack/run-cyclonus-job.sh
See:
- https://github.com/dougsland/kind-sandbox/blob/main/ovn-kubernetes/setup.sh
- https://github.com/ovn-org/ovn-kubernetes/blob/master/.github/workflows/test.yml
- #50 
- https://github.com/ovn-org/ovn-kubernetes/pull/2112
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
TODOs:
=> first pass at ovn action

hack/ovn-kubernetes/cyclonus-job-github-action.yaml
=> skip named-port tests on ovn

hack/antrea/setup-kind.sh
See: https://github.com/K8sbykeshed/k8s-local-dev/pull/1/files
=> fix antrea/KinD setup

.github/workflows/goreleaser.yml
Push a new tag, and goreleaser puts together a new release.
=> add goreleaser github action

.github/workflows/go.yml, .github/workflows/kind_cni_from_source.yml, README.md, go.mod
=> upgrade to go 1.16

hack/ovn-kubernetes/setup-kind.sh
https://github.com/mattfenwick/cyclonus/actions/runs/733001373
=> set ovn cluster name correctly

pkg/cli/generate.go, pkg/generator/tags.go
To print out what *would* be done without actually doing it.
This implicitly triggers mock mode as well.
=> add dry run mode

.github/workflows/kind_cni_from_source.yml, hack/run-cyclonus.sh
=> try piping through cyclonus args to github actions ui

pkg/generator/peerscases.go, pkg/kube/ipaddress.go, pkg/kube/ipaddress_tests.go
=> normalize cidrs for ipblocks

pkg/cli/generate.go
=> move legit output to stdout

pkg/cli/generate.go
=> print args for debugging purposes

pkg/generator/constants.go
=> open port 53 over TCP

pkg/cli/generate.go, pkg/generator/portprotocolcases.go, pkg/generator/tags.go, pkg/generator/testcasegenerator_tests.go
=> add end-port test cases

hack/kind/run-cyclonus.sh, pkg/cli/generate.go, pkg/generator/constants.go, pkg/generator/namespacecases.go, pkg/generator/tags.go, pkg/generator/testcasegenerator.go, pkg/generator/testcasegenerator_tests.go, pkg/kube/constants.go, pkg/kube/ikubernetes.go
=> add test cases for default namespace labels

README.md
for https://github.com/mattfenwick/cyclonus/pull/130
=> add huntergregory to contributors
